# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODc1MTZkZmMzOTg1N2Y5ZDc5ZTZjM2MzMWI2ZWQ1ZTM4ODY0ODM1ZGQ0ZjQ2MDRiM2M2NDE0OTNmMjhlYmYzOWI4N2FmZGZiOTZhMTFhMzQ5NWVlMmYzNzcwNTFmNTNlODAzMDAyMjgzNTZjN2FjM2NhY2MxZmRjYzUyMWQyOWI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
